#!/bin/sh
set -eu

base_url="https://playqueensgame.org"
command="${1:-home}"
value="${2:-}"

case "$command" in
  home)
    printf '%s\n' "$base_url"
    ;;
  page)
    clean=$(printf '%s' "$value" | sed 's#^/*##; s#/*$##')
    if [ -z "$clean" ]; then
      printf '%s\n' "$base_url"
    else
      printf '%s/%s/\n' "$base_url" "$clean"
    fi
    ;;
  play)
    printf '%s/#play\n' "$base_url"
    ;;
  daily)
    printf '%s/daily/\n' "$base_url"
    ;;
  learn)
    printf '%s/learn/\n' "$base_url"
    ;;
  blog)
    printf '%s/blog/\n' "$base_url"
    ;;
  *)
    printf 'usage: playqueensgame-site-kit [home|play|daily|learn|blog|page <slug>]\n' >&2
    exit 64
    ;;
esac
